### ISSUE TITLE
Querying item from structure always yields first structure element

### ISSUE THREAD

**Issue by dinko** [bnomei/kirby3-autoid#20]
I have a structure field with an `autoid`, e.g. like so:

```
typologies:
  label:
    de: Typologien
    en: Typologies
  type: structure
  sortable: false
  sortBy: name asc
  fields:
    autoid:
      type: hidden
      translate: false
    name:
      label:
        de: Name
        en: Name
      type: text
    name_plural:
      label:
        de: Plural
        en: Plural
      type: text
```
and another select field which I fill with the structure values

```
typology_id:
  label:
    de: Typologie
    en: Typology
  type: select
  options: query
  query:
    fetch: site.children.template('products').first.typologies.toStructure
    text: "{{ structureItem.name }}"
    value: "{{ structureItem.autoid }}"
```

So then, the `autoid` gets saved as a key to the structure item.

When I try to retrieve the correct structure item with
```
autoid($page->typology_id())->name()
```
I always get the first item in the structure, not the saved one. Am I doing something wrong?

Thx!
