### ISSUE TITLE
Display autoid entries in panel pages sections

### ISSUE THREAD

**Issue by pierluigi** [bnomei/kirby3-autoid#25]
Is it possible to use autoid to filter pages to be displayed in a pages section inside a custom panel blueprint?

```
sections:
  mysection:
    headline: Foo Pages
    type: pages
    parent: autoid(page.autoid())
```

Notably the `parent` filter [is limited in scope](https://github.com/getkirby/kirby/issues/635) and there's a [plugin](https://github.com/rasteiner/k3-pagesdisplay-section) to do more complex filtering. Is there a way to achieve a filtering based on autoid without using an additional plugin?

**Comment by bnomei** [comment]
i did not try this yet. i will try to find some time this weekend. 
did you try? any errors? maybe it should be `parent: autoid(page.autoid())´?

**Comment by pierluigi** [comment]
Yep – tried that and it just returns 0 results.

**Comment by bnomei** [comment]
sorry for the late response – been super busy. probably the autoid helper is not recognized by the query language. have you tried the field method autoid provides?

`parent: page.autoid()->fromAutoID()`
https://github.com/bnomei/kirby3-autoid/blob/master/index.php#L50

**Comment by pierluigi** [comment]
Unfortunately, I still don't get any results with that. 🤔

**Comment by bnomei** [comment]
try adding this to the autoid plugin index.php config

```
'siteMethods' => [
      'findByAutoID' => function ($id) {
          return autoid($id);
      }
  ]
```

then try a hardcoded id first
`parent: site.findByAutoID('myautoidstring')`
then the dynamic id second
`parent: site.findByAutoID(page.autoid())`

but my guess is that the pages section query is not aware of the current page object. but that information you could use to create an issue at kirby core.

**Comment by pierluigi** [comment]
Still nothing! 😢 Thanks for your support anyway.

**Comment by bnomei** [comment]
form the other plugin i would say the findByAutoID() should return a paginated Pages collection. like [here](https://github.com/rasteiner/k3-pagesdisplay-section/blob/a5bf1e60acef4e59cfca6f057f4b6173cff5e294/src/PagesDisplaySection.php#L36). something like this (untested from memory)...

`return (new Pages([autoid('myautoid')]))->paginate(..???...)`

**Comment by pierluigi** [comment]
Thanks again – but I am not having success. Maybe it's worth taking a couple steps back and try to explain my use case for what I'm trying to build.

I am creating a taxonomy with the following entities: `Artist` and `Release`. The relationship between these entities can be expressed as a `many-to-many` e.g. an `Artist` can have one or many `Releases` and a `Release` can belong to one or many `Artist`.

Using `autoid` I am hoping to preserve the association between these entities:

Artist blueprint
```
# artist.yml
# ...

fields:
  name:
    label: Artist name
    type: text
  autoid:
    type: hidden
    translate: false    
```

Release blueprint
```
# release.yml
# ...

fields:
  artist:
    label: Artist
    type: select
    options: query
    query: site.find('artists').children
    options: query
    query:
      fetch: site.find('artists').children
      text: "{{ page.name }}"
      value: "{{ page.autoid }}"
```

Release template:
`<p>Release: "<?=$page->title()?>", by <?=$page->artist()->fromAutoID()->title() ?></p>`
(e.g. `Release: "Selected Ambient Works", by Aphex Twin`)

I am having issues with the following scenarios:

1) How to show all Releases by Artist inside the Artist blueprint. I can't figure out the right approach to use the `parent` section selector as explained above
2) How to do the same thing inside the Artist template, e.g. `Showing all works by Artist A`. This is because I'm unsure what's the best way to find all Releases and filter them by their autoid field `artist`. `$site->find(`releases`)` will produce the unfiltered list of all Releases.

Maybe I'm confused by the `site`, `pages` and `children` APIs offered by Kirby. It seems as though the `parent` expects a Page object with populated `Children` entries to function. At the same time, I don't want to be forced to create Release pages inside of an Artist page as children, because this is inflexible and prone to duplication (e.g. when 3 Artists collaborated on the same Release).

Any help is sincerely welcome! Thanks again.
