### ISSUE TITLE
Always null with structure field on users

### ISSUE THREAD

**Issue by afbora** [bnomei/kirby3-autoid#33]
I'm using structure field on users like that:

**users/customer.yml**

```
fields:
    addresses:
        label: Addresses
        type: structure
        translate: false
        fields:
            autoId:
                type: hidden
                translate: false
```

`autoId` always null:

```
Addresses:

- 
  autoid: null
  addresstype: shipping
  ...
```
