### ISSUE TITLE
Use autoid as value in files and pages fields?

### ISSUE THREAD

**Issue by lucadorata** [bnomei/kirby3-autoid#53]
Is there any way to enable using autoid values in 'files' & 'pages' fields as described in the wiki for 'option' and 'select' fields by using, ie
```
files:
  type: files
  query:
    fetch: page.images
    value: "{{ file.AUTOID }}"
```
