### ISSUE TITLE
AutoID changed after saving page

### ISSUE THREAD

**Issue by frankmichel** [bnomei/kirby3-autoid#69]
I am not sure what's going on here and if this is expected behaviour. I have a blueprint with basically the following fields configuration:

```
years:
  label: Years
  type: structure
  sortBy: name asc
  sortable: false
  translate: false
  fields:
    name:
      type: text
    autoid:
      type: hidden
      translate: false

events:
  label: Events
  type: structure
  sortBy: name asc
  sortable: false
  translate: false
  fields:
    name:
      type: text
    year:
      type: select
      options: query
      query:
        fetch: page.years.toStructure
        text: '{{ structureItem.name }}'
        value: '{{ structureItem.autoid }}'
    autoid:
      type: hidden
      translate: false
```

So basically I am using the structure **years** to populate the options which are available in the **events** structure. In reality these two structures are on two different tabs, but on the same page. And I think this is part of the problem since the [blueprint example](https://github.com/bnomei/kirby3-autoid/wiki/Examples:-Blueprints#store-multiple-references-to-structureobjects-from-a-different-field-from-another-page) is exactly the same, but on two different pages.

<img width="245" alt="Screenshot 2021-10-29 at 17 30 34" src="https://user-images.githubusercontent.com/236225/139470717-609edbb2-6638-4876-bb3f-5fe04e89a5c7.png">

So, when I add a year to my **years** structure and save the page everything looks fine and the content file gets the new values with an autoid:

<img width="223" alt="Screenshot 2021-10-29 at 17 31 55" src="https://user-images.githubusercontent.com/236225/139470877-cf81079b-5918-4fcd-893e-ad57ecbdb799.png">

However, after changing anything else on the same page and then saving the page again (without reloading) the autoid of the previously saved year will be changed behind the scenes. This causes some issues when trying to use the newly created year in the **events** structure on the same page. A newly created year will be available to be selected as an option, and it will look perfectly when saving the **events** structure.

<img width="239" alt="Screenshot 2021-10-29 at 17 43 04" src="https://user-images.githubusercontent.com/236225/139472276-59f68762-7dd3-40db-8b91-d05a78846b53.png">

But after reloading the page, the year will be empty since the autoid of the year has been changed. I have no idea why the autoid is changing once it has been previously saved. Is there a way to prevent the autoid from being updated/changed once it has been saved?

<img width="254" alt="Screenshot 2021-10-29 at 17 35 26" src="https://user-images.githubusercontent.com/236225/139471705-cd2f3c08-9347-4f1e-ac30-969a09d7cc2a.png">

The autoid has magically changed:
<img width="188" alt="Screenshot 2021-10-29 at 17 35 51" src="https://user-images.githubusercontent.com/236225/139471756-87a057d5-f25e-4781-a821-5e36634d474c.png">

The problem will **not** occur whenever I do the following:

1. add the year to the years structure
2. save the page
3. reload the panel
4. add an entry with the newly added year to the events structure
5. save the page
