### ISSUE TITLE
same autoid on duplicate a structure-item

### ISSUE THREAD

**Issue by bnomei** [bnomei/kirby3-autoid#70]
> Hi @bnomei,
> i am using your autoid-plugin 2.7.7 in a structure-field within site.yml in K3.5. Thank you for that!
> Unfortunately i also have an issue with the same autoid on duplicate a structure-item. The autoid is the same :frowning:
> Because i query/fetch that structure in a select-field by its autoid-value, i am not able to duplicate, otherwise the list is wrong.
> Any idea how to fix that?
> Thx, Dennis

**Comment by bnomei** [comment]
hi dennis,

please post the blueprints for the site.yml and the page where you use that structure.

do you duplicate a structure item on the site object?

**Comment by dennisbaum** [comment]
Hi Bruno, thank you for getting into that issue!

site.yml
```yml
teasers:
  label: Global Teaser
  type: structure
  translate: false
  fields:
    autoid:
      type: hidden
      translate: false
    name:
      label: Name
      type: text
      required: true
    teaserh2:
      label: Headline
      type: text
      required: true
```

after duplicate a teaser in the panel, i get the same autoid in 
site.txt

```txt
Teasers:

- 
  autoid: a6ba57nd
  name: About
  teaserh2: > Lorem Ipsum
  ...
- 
  autoid: onkrq6sb
  name: FAQ
  teaserh2: Noch Fragen?
  ...
- 
  autoid: onkrq6sb
  name: FAQ
  teaserh2: Noch Fragen?
  ...
```

which results in having only two teasers in the following selct-field by 
page-xy.yml

```yml
type: group
fields:
  teaserheadline:
    label: Teaser
    type: headline
  teaserID:
    label:
      de: Teaser auswählen
      en: Select Teaser
    type: select
    required: true
    options: query
    query:
      fetch: site.teasers.toStructure
      text: "{{ structureItem.name }}"
      value: "{{ structureItem.autoid }}"
```
